version: 2.1

commands:
  install-composer-8_0:
    steps:
      - run: | #!bash
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:ondrej/php
          sudo apt-get update
          sudo apt-get install -y php8.0-cli php8.0-common php8.0-mbstring php8.0-intl php8.0-zip php8.0-bcmath php8.0-dom cloc
          curl -s https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

  install-composer-8_1:
    steps:
      - run: | #!bash
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:ondrej/php
          sudo apt-get update
          sudo apt-get install -y php8.0-cli php8.0-common php8.0-mbstring php8.0-intl php8.0-zip php8.0-bcmath php8.0-dom cloc
          curl -s https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

workflows:
  version: 2
  
  build-and-test_8-0:
    jobs:
      - self-test_8-0
  
  build-and-test_8-1:
    jobs:
      - self-test_8-1

jobs:
  self-test:

  self-test_8-0:
    parallelism: 1
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: false
    resource_class: medium
    steps:
      - checkout
      - install-composer-8_0
      - run: composer install --ignore-platform-reqs
      - run: php test/runTests.php

  self-test_8-1:
    parallelism: 1
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: false
    resource_class: medium
    steps:
      - checkout
      - install-composer-8_1
      - run: composer install --ignore-platform-reqs
      - run: php test/runTests.php
